// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoSwuN1593CDD_zPDE-KBlqj-3JN9yEVM',
    appId: '1:1056560713576:web:82444bea662a5a7390d0dd',
    messagingSenderId: '1056560713576',
    projectId: 'style-sphere-d713e',
    authDomain: 'style-sphere-d713e.firebaseapp.com',
    storageBucket: 'style-sphere-d713e.firebasestorage.app',
    measurementId: 'G-PH8SYQVLZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB64eniTIFaI8VGmcjIaqf2vuFKh7F2alY',
    appId: '1:1056560713576:android:1d9fdc493c280aa490d0dd',
    messagingSenderId: '1056560713576',
    projectId: 'style-sphere-d713e',
    storageBucket: 'style-sphere-d713e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoSwuN1593CDD_zPDE-KBlqj-3JN9yEVM',
    appId: '1:1056560713576:web:9ad4b6a52336084290d0dd',
    messagingSenderId: '1056560713576',
    projectId: 'style-sphere-d713e',
    authDomain: 'style-sphere-d713e.firebaseapp.com',
    storageBucket: 'style-sphere-d713e.firebasestorage.app',
    measurementId: 'G-KXD6BYRBK2',
  );
}
